Updates release notes to include all commits since last release

diff --git a/scripts/release-notes b/scripts/release-notes
--- a/scripts/release-notes
+++ b/scripts/release-notes
@@ -4,13 +4,10 @@ set -e
 
 head="${1:-HEAD}"
 
-for sha in `git rev-list -n 100 --first-parent "$head"^`; do
-  previous_tag="$(git tag -l --points-at "$sha" 'v*' 2>/dev/null || true)"
-  [ -z "$previous_tag" ] || break
-done
+previous_tag=$(hub release --include-drafts | head -n 1)
 
 if [ -z "$previous_tag" ]; then
-  echo "Couldn't detect previous version tag" >&2
+  echo "Couldn't detect previous release tag" >&2
   exit 1
 fi
 
